app/protected/controllers/SiteController.php
<?php

use SalestrackerApp\Extension\Authorization\Util\PasswordUtil;
use SalestrackerApp\Extension\Importer\UserImporter;
use SalestrackerApp\Extension\Authorization\UserAuthentication;
use SalestrackerApp\Extension\Authorization\UserProvider;
use SalestrackerApp\Extension\Mailing\MailSender;
use SalestrackerApp\Extension\Spreadsheet\UserSpreadsheetHandler;
use SalestrackerApp\Extension\Upload\FileUploader;
use SalestrackerApp\Extension\Util\ParamFetcher;

class SiteController extends Controller
{
    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    public function accessRules()
    {
        return array(
            array(
                'allow',  // allow all users to perform 'index' and 'view' actions
                'actions' => array('login', 'passwordChange'),
                'users' => array('*'),
            ),
            array(
                'allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('index', 'upload', 'logout', 'page', 'show'),
                'users' => array('@'),
            ),
            array(
                'deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function filters()
    {
        return ['accessControl'];
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex()
    {
        $this->actionShow();
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError()
    {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest) {
                echo $error['message'];
            } else {
                $this->render('error', $error);
            }
        }
    }

    public function actionShow()
    {
        /** @var CHttpRequest $request */
        $request = Yii::app()->request;
        if ($request->getQuery('userId', null)) {
            $users = $this->getUsersFromFile();

            $this->render('fileUserList', ['users' => $users]);

        } else {
            $model = new User('search');
            $model->unsetAttributes();  // clear any default values
            if (isset($_GET['User'])) {
                $model->attributes = $_GET['User'];
            }

            $this->render('userList', ['model' => $model]);
        }
    }

    public function actionUpload()
    {

        $model = new UserFileForm();
        if (isset($_FILES['UserFileForm'])) {
            $importer = $this->getContainer()->get(UserImporter::class);
            $fileUploader = $this->getContainer()->get(FileUploader::class);
            $userProvider = $this->getContainer()->get(UserProvider::class);
            $fileUploader->setMimeTypes(
                [
                    'application/vnd.ms-excel',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                    'application/vnd.oasis.opendocument.spreadsheet',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheetapplication/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                ]
            );

            $filename = $fileUploader->upload($_FILES['UserFileForm']);
            $userFile = new UserFile();
            $userFile->file = $filename;
            $userFile->user_id = $userProvider->getByUsername(Yii::app()->user->id)->id;
            $importer->import(
                $this->getContainer()->get(ParamFetcher::class)->get('uploadFileDestination') . '/' .  $filename
            );

            $userFile->save();

            return $this->redirect(Yii::app()->homeUrl);
        }

        $this->render('upload', ['model' => $model]);
    }

    public function actionLogin()
    {
        $model = new LoginForm;
        /** @var CHttpRequest $request */
        $request = Yii::app()->request;
        if ($request->getParam('ajax', null) === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        if ($request->getParam('LoginForm', null)) {
            $model->attributes = $request->getParam('LoginForm', null);
            if ($model->validate()) {
                $userIdentity = $this->getContainer()->get(UserAuthentication::class);
                $errors = $userIdentity->doAuthenticate($model->username, $model->password);
                if (empty($errors)) {
                    Yii::app()->user->login($userIdentity, (int)($model->rememberMe ?? 0) * 3600 * 24 * 30);
                    $this->redirect(Yii::app()->user->returnUrl);
                }

                $model->addErrors($errors);
                $expiredPasswordError = $model->getErrors('last_password_change_date');
                if (false === empty($expiredPasswordError)) {
                    $userProvider = $this->getContainer()->get(UserProvider::class);
                    $user = $userProvider->getByUsername($model->username);
                    $this->sendChangePasswordMail($user, $this->createPasswordChangeCode($user->id));
                }
            }
        }

        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

    public function actionPasswordChange()
    {
        /** @var CHttpRequest $request */
        $form = new PasswordChangeForm();
        $request = Yii::app()->request;
        $code = (new PasswordChangeCode())->find('code = :code', [':code' => $request->getQuery('code', null)]);
        if (null === $code) {
            return $this->redirect(Yii::app()->homeUrl);
        }

        if (null !== $request->getParam('PasswordChangeForm', null)) {
            $form->attributes = $request->getParam('PasswordChangeForm');
            $passwordUtil = $this->getContainer()->get(PasswordUtil::class);
            $passwordUtil->changePassword($code->user_id, $form);
            if (empty($form->getErrors())) {
                $code->delete();
                return $this->redirect(Yii::app()->homeUrl . '?r=site/login');
            }
        }

        return $this->render('passwordChange', array('model' => $form));
    }

    private function sendChangePasswordMail(\User $user, PasswordChangeCode $code)
    {
        $mailer = $this->getContainer()->get(MailSender::class);
        $mailer->sendPasswordChangeMail($user->email,
            [
                'username' => $user->username,
                'url' => 'http://' . Yii::app()->params['baseUrl'].'?r=site/passwordChange&code='.$code->code,
            ]
        );
    }

    private function createPasswordChangeCode(int $userId): PasswordChangeCode
    {
        $code = new PasswordChangeCode();
        $code->attributes = ['user_id' => $userId, 'code' => sha1(microtime())];
        $code->save();

        return $code;
    }

    private function getUsersFromFile(): array
    {
        $request = Yii::app()->request;
        $userFiles = (new UserFile())->findAll('user_id = :userid', ['userid' => $request->getQuery('userId')]);
        if (false === empty($userFiles)) {
            return $this->getDataFromSheets($userFiles);
        } else {
            return [];
        }
    }

    private function getDataFromSheets(array $userSheets)
    {
        $data = [];
        $uploadDirectory = Yii::app()->params['uploadFileDestination'];
        $spreadsheetHandler = $this->getContainer()->get(UserSpreadsheetHandler::class);
        foreach ($userSheets as $userSheet) {
            $spreadsheetHandler->openSheet($uploadDirectory.'/'.$userSheet->file);
            $data = array_merge($data, array_filter($spreadsheetHandler->getData()));
        }
        return $data;
    }
}

app/protected/views/site/_search.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>128)); ?>
	</div>

    <div class="row">
        <?php echo $form->label($model,'name'); ?>
        <?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128)); ?>
    </div>

    <div class="row">
        <?php echo $form->label($model,'surname'); ?>
        <?php echo $form->textField($model,'surname',array('size'=>60,'maxlength'=>128)); ?>
    </div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>128)); ?>
	</div>

    <div class="row">
        <?php echo $form->label($model,'created_at'); ?>
        <?php echo $form->dateField($model,'created_at'); ?>
    </div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

app/protected/views/site/contact.php
<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

$this->pageTitle=Yii::app()->name . ' - Contact Us';
$this->breadcrumbs=array(
	'Contact',
);
?>

<h1>Contact Us</h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

<p>
If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
</p>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'contact-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'subject'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'body'); ?>
	</div>

	<?php if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		<div>
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint">Please enter the letters as they are shown in the image above.
		<br/>Letters are not case-sensitive.</div>
		<?php echo $form->error($model,'verifyCode'); ?>
	</div>
	<?php endif; ?>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

app/protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

app/protected/views/site/fileUserList.php
<?php
$this->pageTitle=Yii::app()->name . ' - File user list';
$this->breadcrumbs=array(
    'File user list',
);
?>

<h1>File user list</h1>

<table class="items">
    <tbody>
    <?php if (count($users)): ?>
    <?php foreach ($users as $row => $user):
    ?>
        <tr>
            <td><?= $user->getEmail() ?></td>
            <td><?= $user->getName() ?></td>
            <td><?= $user->getSurname() ?></td>
            <td><?= $user->getDateOfBirth()->format('Y-m-d') ?></td>
        </tr>
    <?php endforeach; ?>
    <?php else: ?>
    <p>User has no users in his file</p>
    <?php endif; ?>
    </tbody>
</table>

app/protected/views/site/index.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>

<h1>Welcome to <i><?php echo CHtml::encode(Yii::app()->name); ?></i></h1>

<p>Congratulations! You have successfully created your Yii application.</p>

<p>You may change the content of this page by modifying the following two files:</p>
<ul>
	<li>View file: <code><?php echo __FILE__; ?></code></li>
	<li>Layout file: <code><?php echo $this->getLayoutFile('main'); ?></code></li>
</ul>

<p>For more details on how to further develop this application, please read
the <a href="http://www.yiiframework.com/doc/">documentation</a>.
Feel free to ask in the <a href="http://www.yiiframework.com/forum/">forum</a>,
should you have any questions.</p>

app/protected/views/site/login.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm  */

$this->pageTitle=Yii::app()->name . ' - Login';
$this->breadcrumbs=array(
	'Login',
);
?>

<h1>Login</h1>

<p>Please fill out the following form with your login credentials:</p>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
		<p class="hint">
			Hint: You may login with <kbd>kbaczkiewicz</kbd>/<kbd>1234qwer</kbd> or <kbd>expired</kbd>/<kbd>1234qwer</kbd>.
		</p>
	</div>

	<div class="row rememberMe">
		<?php echo $form->checkBox($model,'rememberMe'); ?>
		<?php echo $form->label($model,'rememberMe'); ?>
		<?php echo $form->error($model,'rememberMe'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Login'); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

app/protected/views/site/passwordChange.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm  */

$this->pageTitle=Yii::app()->name . ' - Password change';
$this->breadcrumbs=array(
    'Password change',
);
?>

<h1>Password change</h1>

<div class="form">
    <?php $form=$this->beginWidget('CActiveForm', array(
        'id'=>'password-change-form',
        'enableClientValidation'=>true,
        'clientOptions'=>array(
            'validateOnSubmit'=>true,
        ),
    )); ?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>

    <div class="row">
        <?php echo $form->labelEx($model,'oldPassword'); ?>
        <?php echo $form->passwordField($model,'oldPassword'); ?>
        <?php echo $form->error($model,'oldPassword'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'newPassword'); ?>
        <?php echo $form->passwordField($model,'newPassword'); ?>
        <?php echo $form->error($model,'newPassword'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'confirmPassword'); ?>
        <?php echo $form->passwordField($model,'confirmPassword'); ?>
        <?php echo $form->error($model,'confirmPassword'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Login'); ?>
    </div>

    <?php $this->endWidget(); ?>
</div><!-- form -->

app/protected/views/site/upload.php
<?php
/* @var $this SiteController */
/* @var $model UserFileForm */
/* @var $form CActiveForm  */

$this->pageTitle=Yii::app()->name . ' - Upload';
$this->breadcrumbs=array(
    'Upload',
);
?>

<h1>Upload</h1>

<div class="form">
    <?php $form=$this->beginWidget('CActiveForm', array(
        'id'=>'login-form',
        'enableClientValidation'=>true,
        'clientOptions'=>array(
            'validateOnSubmit'=>true,
        ),
        'htmlOptions'=>array('enctype'=>'multipart/form-data'),
    )); ?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>

    <div class="row">
        <?php echo $form->labelEx($model,'spreadsheet'); ?>
        <?php echo $form->fileField($model,'spreadsheet'); ?>
        <?php echo $form->error($model,'spreadsheet'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Upload'); ?>
    </div>

    <?php $this->endWidget(); ?>
</div><!-- form -->

app/protected/views/site/userList.php
<?php

$this->pageTitle = Yii::app()->name.' - User list';
$this->breadcrumbs = array(
    'User list',
);

Yii::app()->clientScript->registerScript(
    'search',
    "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#user-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
"
);
?>

<h1>Show users</h1>
<?php echo CHtml::link('Advanced Search', '#', array('class' => 'search-button')); ?>
<div class="search-form" style="display:none">
    <?php $this->renderPartial(
        '_search',
        array(
            'model' => $model,
        )
    ); ?>
</div><!-- search-form -->

<?php $this->widget(
    'zii.widgets.grid.CGridView',
    array(
        'id' => 'user-grid',
        'dataProvider' => $model->search(),
        'filter' => $model,
        'columns' => array(
            'id',
            'username',
            'name',
            'surname',
            'email',
            'created_at',
            array(
                'class' => 'CButtonColumn',
                'template' => '{show}',
                'buttons' => [
                        'show' => [
                                'label' => 'Show',
                                'url'=>'Yii::app()->createUrl("site/show", array("userId"=>$data->id))',

                        ]
                ]
		),
        ),
    )
); ?>